#**Model Predictions**
This notebook focuses on generating predictions on whether a compound in the dataset has antiviral activity using our final models for each target. The dataset was originally too large, so it was fragmented into 10 subsets to facilitate the prediction process, which were finally concatenated. This notebook serves as an example of predictions using all 21 models for each selected target.

# **1. Prepare the environment**

In [ ]:
from pycaret.classification import *
import pandas as pd
from xgboost import *

# **2. Load subset**

In [ ]:
db_predict = pd.read_csv("fragmento_1.csv")
db_predict

# **3. Load models**

In [ ]:
iavpoly_et = load_model('IAV_Poly_model_et_final')
iavpoly_gbc = load_model('IAV_Poly_model_gbc_final')
iavpoly_svm = load_model('IAV_Poly_model_svm_final')
hrv_ada = load_model('HRV_model_ada_final')
hrv_xgboost = load_model('HRV_model_xgboost_final')
hrv_gbc = load_model('HRV_model_gbc_final')
iavm2_qda = load_model('IAV_M2_model_qda_final')
iavm2_dummy = load_model('IAV_M2_model_dummy_final')
iavm2_knn = load_model('IAV_M2_model_knn_final')
sars_svm = load_model('SARS_model_svm_final')
sars_lda = load_model('SARS_model_lda_final')
sars_knn = load_model('SARS_model_knn_final')
sars2_dt = load_model('SARS2_model_dt_final')
sars2_xgboost = load_model('SARS2_model_xgboost_final')
sars2_lightgbm = load_model('SARS2_model_lightgbm_final')
iavneu_rf = load_model('IAV_Neu_model_rf_final')
iavneu_et = load_model('IAV_Neu_model_et_final')
iavneu_lr = load_model('IAV_Neu_model_lr_final')
ibv_ada = load_model('IBV_model_ada_final')
ibv_knn = load_model('IBV_model_knn_final')
ibv_et = load_model('IBV_model_et_final')
models = [iavpoly_svm,
iavpoly_et,
iavpoly_gbc, hrv_gbc,
hrv_ada,
hrv_xgboost, iavm2_qda,
iavm2_dummy,
iavm2_knn, sars_lda,
sars_svm,
sars_knn, sars2_lightgbm,
sars2_dt,
sars2_xgboost, iavneu_rf,
iavneu_lr,
iavneu_et, ibv_ada,
ibv_knn,
ibv_et]

Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded

# **4. Predictions per model**

In [ ]:
predictions_iavpoly_svm = predict_model(iavpoly_svm, data = db_predict)
predictions_iavpoly_svm.rename(columns={'prediction_label': 'prediction_label_iavpoly_svm', 'prediction_score': 'prediction_score_iavpoly_svm'}, inplace=True)
predictions_iavpoly_svm

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavpoly_svm
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,1
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,0,1,0,0,0
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
predictions_iavpoly_et = predict_model(iavpoly_et, data= db_predict)
predictions_iavpoly_et.rename(columns={'prediction_label': 'prediction_label_iavpoly_et', 'prediction_score': 'prediction_score_iavpoly_et'}, inplace=True)
predictions_iavpoly_et

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavpoly_et,prediction_score_iavpoly_et
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.58
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,0.55
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.57
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.69
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.80
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.66
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.75
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.87
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.60

In [ ]:
predictions_iavpoly_gbc = predict_model(iavpoly_gbc, data= db_predict)
predictions_iavpoly_gbc.rename(columns={'prediction_label': 'prediction_label_iavpoly_gbc', 'prediction_score': 'prediction_score_iavpoly_gbc'}, inplace=True)
predictions_iavpoly_gbc

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavpoly_gbc,prediction_score_iavpoly_gbc
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.9625
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,0.8332
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,1,0.6588
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.6649
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,1,0.6588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.9809
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.9657
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.9668
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.9635
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.5766

In [ ]:
predictions_hrv_gbc = predict_model(hrv_gbc, data= db_predict)
predictions_hrv_gbc.rename(columns={'prediction_label': 'prediction_label_hrv_gbc', 'prediction_score': 'prediction_score_hrv_gbc'}, inplace=True)
predictions_hrv_gbc

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_hrv_gbc,prediction_score_hrv_gbc
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.8126
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,0.6789
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,1,0.7621
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.9639
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,1,0.7621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.8524
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.7389
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.7724
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.9587
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.8030

In [ ]:
predictions_hrv_ada = predict_model(hrv_ada, data= db_predict)
predictions_hrv_ada.rename(columns={'prediction_label': 'prediction_label_hrv_ada', 'prediction_score': 'prediction_score_hrv_ada'}, inplace=True)
predictions_hrv_ada

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_hrv_ada,prediction_score_hrv_ada
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.5412
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.6553
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.6553
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.5541
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.6553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.5288
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.5150
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.5566
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.5567
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.5352

In [ ]:
predictions_hrv_xgboost = predict_model(hrv_xgboost, data= db_predict)
predictions_hrv_xgboost.rename(columns={'prediction_label': 'prediction_label_hrv_xgboost', 'prediction_score': 'prediction_score_hrv_xgboost'}, inplace=True)
predictions_hrv_xgboost

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_hrv_xgboost,prediction_score_hrv_xgboost
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.9794
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,0.7948
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,1,0.9494
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.9939
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,1,0.9099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.9528
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.8970
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.9526
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.9983
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.9857

In [ ]:
predictions_iavm2_qda = predict_model(iavm2_qda, data= db_predict)
predictions_iavm2_qda.rename(columns={'prediction_label': 'prediction_label_iavm2_qda', 'prediction_score': 'prediction_score_iavm2_qda'}, inplace=True)
predictions_iavm2_qda

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavm2_qda,prediction_score_iavm2_qda
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,1.0000
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,1.0000
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,1,1.0000
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.9998
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,1,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,1.0000
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,1.0000
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,1,1.0000
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,1.0000
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,1.0000

In [ ]:
predictions_iavm2_dummy = predict_model(iavm2_dummy, data= db_predict)
predictions_iavm2_dummy.rename(columns={'prediction_label': 'prediction_label_iavm2_dummy', 'prediction_score': 'prediction_score_iavm2_dummy'}, inplace=True)
predictions_iavm2_dummy

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavm2_dummy,prediction_score_iavm2_dummy
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,1.0
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,1,1.0
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,1,1.0
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,1.0
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,1.0
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,1.0
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,1,1.0
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,1.0
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,1.0

In [ ]:
predictions_iavm2_knn = predict_model(iavm2_knn, data= db_predict)
predictions_iavm2_knn.rename(columns={'prediction_label': 'prediction_label_iavm2_knn', 'prediction_score': 'prediction_score_iavm2_knn'}, inplace=True)
predictions_iavm2_knn

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavm2_knn,prediction_score_iavm2_knn
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,1.000
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,1.000
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,1.000
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,1.000
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,1.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.875
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.625
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.875
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.875
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.750

In [ ]:
predictions_sars_lda = predict_model(sars_lda, data= db_predict)
predictions_sars_lda.rename(columns={'prediction_label': 'prediction_label_sars_lda', 'prediction_score': 'prediction_score_sars_lda'}, inplace=True)
predictions_sars_lda

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars_lda,prediction_score_sars_lda
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,1.0
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,1.0
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,1.0
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,1.0
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,1.0
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,1.0
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,1.0

In [ ]:
predictions_sars_svm = predict_model(sars_svm, data= db_predict)
predictions_sars_svm.rename(columns={'prediction_label': 'prediction_label_sars_svm', 'prediction_score': 'prediction_score_sars_svm'}, inplace=True)
predictions_sars_svm

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars_svm
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,0,1,0,0,0
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
predictions_sars_knn = predict_model(sars_knn, data= db_predict)
predictions_sars_knn.rename(columns={'prediction_label': 'prediction_label_sars_knn', 'prediction_score': 'prediction_score_sars_knn'}, inplace=True)
predictions_sars_knn

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars_knn,prediction_score_sars_knn
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.750
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.625
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.625
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.875
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.625
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.625
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.625
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.625
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.625

In [ ]:
predictions_sars2_lightgbm = predict_model(sars2_lightgbm, data= db_predict)
predictions_sars2_lightgbm.rename(columns={'prediction_label': 'prediction_label_sars2_lightgbm', 'prediction_score': 'prediction_score_sars2_lightgbm'}, inplace=True)
predictions_sars2_lightgbm

[LightGBM] [Warning] feature_fraction is set=0.5, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] bagging_fraction is set=0.9, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9
[LightGBM] [Warning] feature_fraction is set=0.5, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] bagging_fraction is set=0.9, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars2_lightgbm,prediction_score_sars2_lightgbm
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.9905
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9702
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9505
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.9941
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.9045
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.6172
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,1,0.6794
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.9859
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.6936

In [ ]:
predictions_sars2_dt = predict_model(sars2_dt, data= db_predict)
predictions_sars2_dt.rename(columns={'prediction_label': 'prediction_label_sars2_dt', 'prediction_score': 'prediction_score_sars2_dt'}, inplace=True)
predictions_sars2_dt

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars2_dt,prediction_score_sars2_dt
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,1.0
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,1.0
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,1.0
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,1.0
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,1.0
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,1.0
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,1.0

In [ ]:
predictions_sars2_xgboost = predict_model(sars2_xgboost, data= db_predict)
predictions_sars2_xgboost.rename(columns={'prediction_label': 'prediction_label_sars2_xgboost', 'prediction_score': 'prediction_score_sars2_xgboost'}, inplace=True)
predictions_sars2_xgboost

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_sars2_xgboost,prediction_score_sars2_xgboost
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,1,0.9962
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9724
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.8739
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,1,0.9998
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.9864
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.8585
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,1,0.8368
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.9993
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.9917

In [ ]:
predictions_iavneu_rf = predict_model(iavneu_rf, data= db_predict)
predictions_iavneu_rf.rename(columns={'prediction_label': 'prediction_label_iavneu_rf', 'prediction_score': 'prediction_score_iavneu_rf'}, inplace=True)
predictions_iavneu_rf

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavneu_rf,prediction_score_iavneu_rf
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.90
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.60
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.69
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.90
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.61
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.71
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.63
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.80
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.52

In [ ]:
predictions_iavneu_lr = predict_model(iavneu_lr, data= db_predict)
predictions_iavneu_lr.rename(columns={'prediction_label': 'prediction_label_iavneu_lr', 'prediction_score': 'prediction_score_iavneu_lr'}, inplace=True)
predictions_iavneu_lr

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavneu_lr,prediction_score_iavneu_lr
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.9374
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9992
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9615
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.9889
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.9998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.8179
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.6941
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.9821
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.7203
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,1,0.9937

In [ ]:
predictions_iavneu_et = predict_model(iavneu_et, data= db_predict)
predictions_iavneu_et.rename(columns={'prediction_label': 'prediction_label_iavneu_et', 'prediction_score': 'prediction_score_iavneu_et'}, inplace=True)
predictions_iavneu_et

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_iavneu_et,prediction_score_iavneu_et
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.91
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.63
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.61
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.98
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.54
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.70
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.70
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.76
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.56

In [ ]:
predictions_ibv_ada = predict_model(ibv_ada, data= db_predict)
predictions_ibv_ada.rename(columns={'prediction_label': 'prediction_label_ibv_ada', 'prediction_score': 'prediction_score_ibv_ada'}, inplace=True)
predictions_ibv_ada

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_ibv_ada,prediction_score_ibv_ada
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.5118
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.5106
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.5186
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.5219
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.5401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,1,0.5060
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.6141
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.5184
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,1,0.5112
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.6740

In [ ]:
predictions_ibv_knn = predict_model(ibv_knn, data= db_predict)
predictions_ibv_knn.rename(columns={'prediction_label': 'prediction_label_ibv_knn', 'prediction_score': 'prediction_score_ibv_knn'}, inplace=True)
predictions_ibv_knn

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_ibv_knn,prediction_score_ibv_knn
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.6250
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.7500
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.8125
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.6250
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.8125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.8125
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,0,0.5625
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.6875
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.6875
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.8125

In [ ]:
predictions_ibv_et = predict_model(ibv_et, data= db_predict)
predictions_ibv_et.rename(columns={'prediction_label': 'prediction_label_ibv_et', 'prediction_score': 'prediction_score_ibv_et'}, inplace=True)
predictions_ibv_et

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,2040,2041,2042,2043,2044,2045,2046,2047,prediction_label_ibv_et,prediction_score_ibv_et
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089203,0.117647,4,0,3,...,0,0,0,0,0,0,0,0,0,0.62
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179077,0.333333,8,1,4,...,0,0,0,0,0,0,0,0,0,0.63
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179413,0.347826,8,1,4,...,0,0,0,0,0,0,0,0,0,0.71
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047348,0.100000,3,1,2,...,0,0,0,0,0,0,0,0,0,0.62
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163757,0.318182,8,1,4,...,0,0,0,0,0,0,0,0,0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104156,0.222222,5,1,4,...,0,0,0,0,0,0,0,0,0,0.70
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073822,0.350000,6,2,3,...,0,0,0,0,0,0,0,0,1,0.67
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153198,0.444444,7,2,3,...,0,0,0,0,0,1,0,0,0,0.56
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116425,0.166667,5,0,4,...,0,0,0,0,0,0,0,0,0,0.76
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083740,0.000000,6,1,5,...,0,0,0,0,0,0,0,0,0,0.72

# **5. Extraction of relevant columns**

In [ ]:
# List to hold the DataFrames (assuming they are already loaded)
dataframes = [predictions_iavpoly_svm,
predictions_iavpoly_et,
predictions_iavpoly_gbc, predictions_hrv_gbc,
predictions_hrv_ada,
predictions_hrv_xgboost, predictions_iavm2_qda,
predictions_iavm2_dummy,
predictions_iavm2_knn, predictions_sars_lda,
predictions_sars_svm,
predictions_sars_knn, predictions_sars2_lightgbm,
predictions_sars2_dt,
predictions_sars2_xgboost, predictions_iavneu_rf,
predictions_iavneu_lr,
predictions_iavneu_et, predictions_ibv_ada,
predictions_ibv_knn,
predictions_ibv_et]

# List to hold the last two columns
last_two_cols = []

# Loop through each DataFrame to extract the last two columns
for df in dataframes:
    last_two_cols.append(df.iloc[:, -2:])  # Get the last two columns

# Concatenate all the last two columns into one DataFrame
db_predict_final = pd.concat(last_two_cols, axis=1).reset_index(drop=True)

In [ ]:
db_predict_final

,2047,prediction_label_iavpoly_svm,prediction_label_iavpoly_et,prediction_score_iavpoly_et,prediction_label_iavpoly_gbc,prediction_score_iavpoly_gbc,prediction_label_hrv_gbc,prediction_score_hrv_gbc,prediction_label_hrv_ada,prediction_score_hrv_ada,...,prediction_label_iavneu_lr,prediction_score_iavneu_lr,prediction_label_iavneu_et,prediction_score_iavneu_et,prediction_label_ibv_ada,prediction_score_ibv_ada,prediction_label_ibv_knn,prediction_score_ibv_knn,prediction_label_ibv_et,prediction_score_ibv_et
0,0,1,0,0.58,1,0.9625,1,0.8126,1,0.5412,...,0,0.9374,0,0.91,0,0.5118,0,0.6250,0,0.62
1,0,0,1,0.55,1,0.8332,1,0.6789,0,0.6553,...,0,0.9992,0,0.63,0,0.5106,0,0.7500,0,0.63
2,0,0,0,0.57,1,0.6588,1,0.7621,0,0.6553,...,0,0.9615,0,0.61,0,0.5186,0,0.8125,0,0.71
3,0,0,0,0.69,1,0.6649,1,0.9639,1,0.5541,...,0,0.9889,0,0.98,0,0.5219,0,0.6250,0,0.62
4,0,0,0,0.56,1,0.6588,1,0.7621,0,0.6553,...,0,0.9998,0,0.66,0,0.5401,0,0.8125,0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0,0,0,0.80,0,0.9809,1,0.8524,1,0.5288,...,0,0.8179,1,0.54,1,0.5060,0,0.8125,0,0.70
24996,0,0,0,0.66,0,0.9657,1,0.7389,1,0.5150,...,1,0.6941,0,0.70,1,0.6141,0,0.5625,1,0.67
24997,0,0,0,0.75,0,0.9668,0,0.7724,0,0.5566,...,0,0.9821,0,0.70,0,0.5184,0,0.6875,0,0.56
24998,0,0,0,0.87,0,0.9635,1,0.9587,1,0.5567,...,1,0.7203,0,0.76,1,0.5112,0,0.6875,0,0.76
24999,0,0,0,0.60,1,0.5766,1,0.8030,1,0.5352,...,1,0.9937,0,0.56,0,0.6740,0,0.8125,0,0.72

In [ ]:
db_predict_final = pd.concat([db_predict, db_predict_final], axis=1).reset_index(drop=True)
db_predict_final

,SMILES,Canonical_SMILES_STD,ID,DB,Num_Reps,mw,fsp3,n_lipinski_hba,n_lipinski_hbd,n_rings,...,prediction_label_iavneu_lr,prediction_score_iavneu_lr,prediction_label_iavneu_et,prediction_score_iavneu_et,prediction_label_ibv_ada,prediction_score_ibv_ada,prediction_label_ibv_knn,prediction_score_ibv_knn,prediction_label_ibv_et,prediction_score_ibv_et
0,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,COc1cc(OC)c2c(=O)cc(-c3ccccc3)oc2c1,"79279_OT_DLGC, 421_LC_HFL, 3434_LC_polL, 371_L...","OT_DLGC, LC_HFL, LC_polL, LC_covL, LC_MASS, LC...",9,282.089209,0.117647,4,0,3,...,0,0.9374,0,0.91,0,0.5118,0,0.6250,0,0.62
1,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,COc1cccc(C2C(C(=O)c3ccc4c(c3)OCCO4)=C(O)C(=O)N...,"41975_OT_DLGC, 1194_LC_HFL, 5715_LC_polsL, 297...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",9,438.179087,0.333333,8,1,4,...,0,0.9992,0,0.63,0,0.5106,0,0.7500,0,0.63
2,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,CN(C)CCCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1...,"38280_ChD_AvL, 41001_OT_DLGC, 489_LC_HFL, 2810...","ChD_AvL, OT_DLGC, LC_HFL, LC_polsL, LC_covL, L...",9,423.179421,0.347826,8,1,4,...,0,0.9615,0,0.61,0,0.5186,0,0.8125,0,0.71
3,Cc1cc(=O)oc2cc(O)ccc12,Cc1cc(=O)oc2cc(O)ccc12,"20716_ChD_covL, 31050_OT_DLGC, 757_LC_HFL, 396...","ChD_covL, OT_DLGC, LC_HFL, LC_polsL, LC_MASS, ...",9,176.047344,0.100000,3,1,2,...,0,0.9889,0,0.98,0,0.5219,0,0.6250,0,0.62
4,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,CN(C)CCN1C(=O)C(O)=C(C(=O)c2ccc3c(c2)OCCO3)C1c...,"40935_OT_DLGC, 483_LC_HFL, 2769_LC_polsL, 322_...","OT_DLGC, LC_HFL, LC_polsL, LC_covL, LC_MASS, L...",8,409.163771,0.318182,8,1,4,...,0,0.9998,0,0.66,0,0.5401,0,0.8125,0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Cl.O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,O=C(Nc1nc2c(s1)CN(Cc1ccccc1)CC2)c1ccco1,"1227_LC_plpL, 15808_LC_MASS","LC_plpL, LC_MASS",2,339.104148,0.222222,5,1,4,...,0,0.8179,1,0.54,1,0.5060,0,0.8125,0,0.70
24996,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,CCOC(=O)c1c(NC(=O)CC2Sc3ccc(C(F)(F)F)cc3NC2=O)...,"42857_ChD_AvL, 8926_OT_DLGC","ChD_AvL, OT_DLGC",2,472.073834,0.350000,6,2,3,...,1,0.6941,0,0.70,1,0.6141,0,0.5625,1,0.67
24997,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,CC(=O)c1ccc(NC(=O)CN2C(=O)NC3(CCCCC3)C2=O)cc1,"51292_ChD_AvL, 1150_LC_polsL","ChD_AvL, LC_polsL",2,343.153206,0.444444,7,2,3,...,0,0.9821,0,0.70,0,0.5184,0,0.6875,0,0.56
24998,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,CCOC(=O)Cn1c2ccccc2c2nc3ccccc3nc21,"42854_ChD_AvL, 38510_OT_DLGC","ChD_AvL, OT_DLGC",2,305.116427,0.166667,5,0,4,...,1,0.7203,0,0.76,1,0.5112,0,0.6875,0,0.76
24999,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,O=C(Nc1ccccc1-c1cn2ccccc2n1)c1cc(-c2cccs2)on1,"1226_LC_plpL, 22911_LC_MASS","LC_plpL, LC_MASS",2,386.083747,0.000000,6,1,5,...,1,0.9937,0,0.56,0,0.6740,0,0.8125,0,0.72

In [ ]:
db_predict_final.columns

Index(['SMILES', 'Canonical_SMILES_STD', 'ID', 'DB', 'Num_Reps', 'mw', 'fsp3',
       'n_lipinski_hba', 'n_lipinski_hbd', 'n_rings',
       ...
       'prediction_label_iavneu_lr', 'prediction_score_iavneu_lr',
       'prediction_label_iavneu_et', 'prediction_score_iavneu_et',
       'prediction_label_ibv_ada', 'prediction_score_ibv_ada',
       'prediction_label_ibv_knn', 'prediction_score_ibv_knn',
       'prediction_label_ibv_et', 'prediction_score_ibv_et'],
      dtype='object', length=2117)

# **6. Save first subset predictions**

In [ ]:
db_predict_final.to_csv("final_predictions_2048_f1.csv", index = False)